### ISSUE TITLE
As a user I want to see all my orders

### ISSUE THREAD

**Issue by emrb9** [AgnesCroteau/SOEN-341-PROJECT-GROUP-K#101]
This user story relates to core feature #99 

DESCRIPTION:

As a user, I can see all the orders I have placed in a list. This means, that, when I am logged in, the navbar shows a button  "My Orders" which will show a list of all the orders I have placed. For each item in this list, there will be a "cancel" button which will delete an order from database by clicking.

PRIORITY:

RISKS
- If there is a logical bug in the backend, the seller might see once the My Orders button is clicked see orders from other sellers.
- If there is a logical bug in the backend, the seller one the Cancel order is clicked cancel orders from other sellers.

STORY POINTS: 5

This task requires fairly new features, such as getting all the orders that match a user's ID. It also requires to put a delete button that will delete the corresponding order in the backend.

**Comment by nolanbastien** [comment]
Adding a new feature: A user can delete an order he/she has placed.
